# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client_server.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'client_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63lient_server.proto\x12\x05video\"\xb4\x01\n\rClientMessage\x12$\n\x05start\x18\x01 \x01(\x0b\x32\x13.video.StartRequestH\x00\x12\"\n\x04stop\x18\x02 \x01(\x0b\x32\x12.video.StopRequestH\x00\x12$\n\x05pause\x18\x03 \x01(\x0b\x32\x13.video.PauseRequestH\x00\x12(\n\x07unpause\x18\x04 \x01(\x0b\x32\x15.video.UnpauseRequestH\x00\x42\t\n\x07payload\"\xc2\x01\n\x0eServerMessage1\x12)\n\x0bvideo_chunk\x18\x01 \x01(\x0b\x32\x12.video.VideoChunk1H\x00\x12:\n\x14server_pause_request\x18\x02 \x01(\x0b\x32\x1a.video.ServerPauseRequest1H\x00\x12>\n\x16server_unpause_request\x18\x03 \x01(\x0b\x32\x1c.video.ServerUnpauseRequest1H\x00\x42\t\n\x07payload\"(\n\x13ServerPauseRequest1\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"*\n\x15ServerUnpauseRequest1\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"!\n\x0cStartRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"\x1d\n\x0bStopRequest\x12\x0e\n\x06reason\x18\x01 \x01(\t\"!\n\x0cPauseRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"#\n\x0eUnpauseRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"\x1d\n\x0bVideoChunk1\x12\x0e\n\x06\x66rames\x18\x01 \x01(\x0c\x32P\n\x13\x43lientServerService\x12\x39\n\x06Stream\x12\x14.video.ClientMessage\x1a\x15.video.ServerMessage1(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTMESSAGE']._serialized_start=31
  _globals['_CLIENTMESSAGE']._serialized_end=211
  _globals['_SERVERMESSAGE1']._serialized_start=214
  _globals['_SERVERMESSAGE1']._serialized_end=408
  _globals['_SERVERPAUSEREQUEST1']._serialized_start=410
  _globals['_SERVERPAUSEREQUEST1']._serialized_end=450
  _globals['_SERVERUNPAUSEREQUEST1']._serialized_start=452
  _globals['_SERVERUNPAUSEREQUEST1']._serialized_end=494
  _globals['_STARTREQUEST']._serialized_start=496
  _globals['_STARTREQUEST']._serialized_end=529
  _globals['_STOPREQUEST']._serialized_start=531
  _globals['_STOPREQUEST']._serialized_end=560
  _globals['_PAUSEREQUEST']._serialized_start=562
  _globals['_PAUSEREQUEST']._serialized_end=595
  _globals['_UNPAUSEREQUEST']._serialized_start=597
  _globals['_UNPAUSEREQUEST']._serialized_end=632
  _globals['_VIDEOCHUNK1']._serialized_start=634
  _globals['_VIDEOCHUNK1']._serialized_end=663
  _globals['_CLIENTSERVERSERVICE']._serialized_start=665
  _globals['_CLIENTSERVERSERVICE']._serialized_end=745
# @@protoc_insertion_point(module_scope)
