version: '3.8'

services:
  client1:
    build:
      context: ./client
    container_name: client1
    depends_on:
      - server
    volumes:
      - ./shared_output1:/output
  
  client2:
    build:
      context: ./client
    container_name: client2
    depends_on:
      - server
    volumes:
      - ./shared_output2:/output

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "50001:50001"
    depends_on:
      - streamer

  streamer:
    build:
      context: ./streamer
    container_name: streamer
    ports:
      - "50002:50002"
