# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_streamer.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'server_streamer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15server_streamer.proto\x12\x05video\"\x88\x02\n\rServerMessage\x12\x39\n\x14server_start_request\x18\x01 \x01(\x0b\x32\x19.video.ServerStartRequestH\x00\x12\x37\n\x13server_stop_request\x18\x02 \x01(\x0b\x32\x18.video.ServerStopRequestH\x00\x12\x39\n\x14server_pause_request\x18\x03 \x01(\x0b\x32\x19.video.ServerPauseRequestH\x00\x12=\n\x16server_unpause_request\x18\x04 \x01(\x0b\x32\x1b.video.ServerUnpauseRequestH\x00\x42\t\n\x07payload\"\xc8\x01\n\x0fStreamerMessage\x12(\n\x0bvideo_chunk\x18\x01 \x01(\x0b\x32\x11.video.VideoChunkH\x00\x12=\n\x16streamer_pause_request\x18\x02 \x01(\x0b\x32\x1b.video.StreamerPauseRequestH\x00\x12\x41\n\x18streamer_unpause_request\x18\x03 \x01(\x0b\x32\x1d.video.StreamerUnpauseRequestH\x00\x42\t\n\x07payload\"\x14\n\x12ServerStartRequest\"\x13\n\x11ServerStopRequest\"\'\n\x12ServerPauseRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\")\n\x14StreamerPauseRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\")\n\x14ServerUnpauseRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"+\n\x16StreamerUnpauseRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"\x1c\n\nVideoChunk\x12\x0e\n\x06\x66rames\x18\x01 \x01(\x0c\x32S\n\x15ServerStreamerService\x12:\n\x06Stream\x12\x14.video.ServerMessage\x1a\x16.video.StreamerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_streamer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERMESSAGE']._serialized_start=33
  _globals['_SERVERMESSAGE']._serialized_end=297
  _globals['_STREAMERMESSAGE']._serialized_start=300
  _globals['_STREAMERMESSAGE']._serialized_end=500
  _globals['_SERVERSTARTREQUEST']._serialized_start=502
  _globals['_SERVERSTARTREQUEST']._serialized_end=522
  _globals['_SERVERSTOPREQUEST']._serialized_start=524
  _globals['_SERVERSTOPREQUEST']._serialized_end=543
  _globals['_SERVERPAUSEREQUEST']._serialized_start=545
  _globals['_SERVERPAUSEREQUEST']._serialized_end=584
  _globals['_STREAMERPAUSEREQUEST']._serialized_start=586
  _globals['_STREAMERPAUSEREQUEST']._serialized_end=627
  _globals['_SERVERUNPAUSEREQUEST']._serialized_start=629
  _globals['_SERVERUNPAUSEREQUEST']._serialized_end=670
  _globals['_STREAMERUNPAUSEREQUEST']._serialized_start=672
  _globals['_STREAMERUNPAUSEREQUEST']._serialized_end=715
  _globals['_VIDEOCHUNK']._serialized_start=717
  _globals['_VIDEOCHUNK']._serialized_end=745
  _globals['_SERVERSTREAMERSERVICE']._serialized_start=747
  _globals['_SERVERSTREAMERSERVICE']._serialized_end=830
# @@protoc_insertion_point(module_scope)
