# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_streamer.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'server_streamer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15server_streamer.proto\x12\x05video\"\x96\x01\n\x15ServerStreamerMessage\x12\x39\n\x14server_start_request\x18\x01 \x01(\x0b\x32\x19.video.ServerStartRequestH\x00\x12\x37\n\x13server_stop_request\x18\x02 \x01(\x0b\x32\x18.video.ServerStopRequestH\x00\x42\t\n\x07payload\"z\n\x15StreamerServerMessage\x12)\n\x04info\x18\x01 \x01(\x0b\x32\x19.video.StreamerServerInfoH\x00\x12+\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x1a.video.StreamerServerChunkH\x00\x42\t\n\x07payload\"\x14\n\x12ServerStartRequest\"\x13\n\x11ServerStopRequest\"$\n\x13StreamerServerChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"\"\n\x12StreamerServerInfo\x12\x0c\n\x04info\x18\x01 \x01(\t2a\n\x15ServerStreamerService\x12H\n\x06Stream\x12\x1c.video.ServerStreamerMessage\x1a\x1c.video.StreamerServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_streamer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERSTREAMERMESSAGE']._serialized_start=33
  _globals['_SERVERSTREAMERMESSAGE']._serialized_end=183
  _globals['_STREAMERSERVERMESSAGE']._serialized_start=185
  _globals['_STREAMERSERVERMESSAGE']._serialized_end=307
  _globals['_SERVERSTARTREQUEST']._serialized_start=309
  _globals['_SERVERSTARTREQUEST']._serialized_end=329
  _globals['_SERVERSTOPREQUEST']._serialized_start=331
  _globals['_SERVERSTOPREQUEST']._serialized_end=350
  _globals['_STREAMERSERVERCHUNK']._serialized_start=352
  _globals['_STREAMERSERVERCHUNK']._serialized_end=388
  _globals['_STREAMERSERVERINFO']._serialized_start=390
  _globals['_STREAMERSERVERINFO']._serialized_end=424
  _globals['_SERVERSTREAMERSERVICE']._serialized_start=426
  _globals['_SERVERSTREAMERSERVICE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
